function [posterior, class1_labels,class2_labels] = gmm_bays_classify_3c(m0,data1,data2, sD1,sM1, sD2,sM2)
% classifys given data into two classes based on the gaussian kernal parameters seleclted for both classes
% All the map units in both Maps are taken as the centres of gaussian kernals, 
% and the parameters of the mixture model are learned which are then used in the Basian frame work classification

%   data1 = matrix
          %the data to be classified, should have the same dimentionality as of the first training class (sD1,sM1)
%   data2 = matrix
          %the data to be classified, should have the same dimentionality as of the second training class (sD2,sM2)
%   sD1  = Data Struct 1
%   sM1  = Map Struct 1
%   sD2  = Data Struct 2
%   sM2  = Map Struct 2

%   Posteriors = Posterior probablities of the data for two classes
%   class = 0 and 1 for two classes
% Created by Mujahid Sultan July 15, 2002
% msultan@uhnres.utoronto.ca
%

% find the kernal parameters for both classes
[K1, P1]= som_estimate_gmm(sM1,sD1);
[K2, P2]= som_estimate_gmm(sM2,sD2);

% classify the data
[posterior, posterior_class]=gmm_em_prob_classifier_3c(K1,P1,K2,P2,sM1,sM2,data1,data2);

% class1_labels are the labels of sM.codebook which were generated by mixture model_1 
class1_labels = m0(posterior_class(:,1)==1);
% class2_labels are the labels of sM.codebook which were generated by mixture model_2
class2_labels = m0(posterior_class(:,2)==1);
%[class11,ind_c11,class12,ind_c12,class012,ind_c012]= gene_label_comp_3(m0,class1_labels,class2_labels);  
% % plot data
% figure(111)
% plot (posterior_class(:,1),'.b')
% hold on
% plot (posterior_class(:,2),'.r')
